export const store = [
  {
    id: 1,
    name: 'Red Love Cup',
    img: '/images/items/01.png',
    description: '',
    price: '',
    discountPrice: 25.00,
    oldPrice: 37.00,
    actualPrice: 25.00,
    amountOfProduct: 10,
    size: 'M',
  },

  {
    id: 2,
    name: 'Black Tea Cup',
    img: '/images/items/02.png',
    description: '',
    price: '',
    discountPrice: `$${15.00}`,
    oldPrice: `$${19.00}USD`,
    actualPrice: 15.00,
    amountOfProduct: 15,
    size: 'M',
  },

  {
    id: 3,
    name: 'B&W Essentials Mug',
    img: '/images/items/03.png',
    description: '',
    price: `$${19.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 19.00,
    amountOfProduct: 10,
    size: 'S',
  },

  {
    id: 4,
    name: 'Winter Style Mug',
    img: '/images/items/04.png',
    description: '',
    price: `$${25.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 25.00,
    amountOfProduct: 30,
    size: 'L',
  },

  {
    id: 5,
    name: 'Ceramic Tea',
    img: '/images/items/05.png',
    description: '',
    price: `$${46.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 46.00,
    amountOfProduct: 10,
    size: 'M',
  },

  {
    id: 6,
    name: 'No Handle Bar Cup',
    img: '/images/items/06.png',
    description: '',
    price: `$${34.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 34.00,
    amountOfProduct: 10,
    size: 'S',
  },

  {
    id: 7,
    name: 'Espresso Cup by Mugs.co',
    img: '/images/items/07.png',
    description: '',
    price: `$${25.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 25.00,
    amountOfProduct: 10,
    size: 'L',
  },

  {
    id: 8,
    name: 'Pink Premium Ceramic',
    img: '/images/items/08.png',
    description: '',
    price: `$${25.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 25.00,
    amountOfProduct: 10,
    size: 'S',
  },

  {
    id: 9,
    name: 'Summer Designer Cup',
    img: '/images/items/09.png',
    description: '',
    price: `$${25.00}USD`,
    discountPrice: '',
    oldPrice: '',
    actualPrice: 25.00,
    amountOfProduct: 10,
    size: 'L',
  },
];
